/**
 * MailCraft Studio - Enterprise Deployment & Desktop Signature File Exporter
 * Generates ready-to-run Google Apps Scripts, Microsoft 365 Exchange PowerShell,
 * macOS Apple Mail (.mailsignature), Outlook (.htm), and Thunderbird files.
 * 100% client-side compilation & zero data transmission.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], factory);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.AdminTools = factory();
  }
}(typeof self !== 'undefined' ? self : this, function() {
  'use strict';

  function generateUUID() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      const r = Math.random() * 16 | 0;
      const v = c === 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16).toUpperCase();
    });
  }

  function downloadTextFile(content, filename, mimeType = 'text/plain;charset=utf-8') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 200);
  }

  const AdminTools = {
    /**
     * Generate macOS Apple Mail .mailsignature content with RFC 822 / MIME header wrapper
     */
    generateAppleMailSignature(htmlContent) {
      const uuid = generateUUID();
      const headers = [
        'Content-Type: text/html; charset=utf-8',
        'Content-Transfer-Encoding: 7bit',
        `Message-Id: <${uuid}@mailcraft.local>`,
        'Mime-Version: 1.0 (Apple Message signature)',
        '',
        htmlContent
      ];
      return headers.join('\r\n');
    },

    /**
     * Download Apple Mail .mailsignature file
     */
    downloadAppleMailSignature(htmlContent, filename = 'signature') {
      const content = this.generateAppleMailSignature(htmlContent);
      const uuid = generateUUID();
      downloadTextFile(content, `${uuid}.mailsignature`, 'application/octet-stream');
    },

    /**
     * Generate Windows Outlook .htm signature file
     */
    generateOutlookHtm(htmlContent) {
      return `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">\r\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8"></HEAD><BODY>\r\n${htmlContent}\r\n</BODY></HTML>`;
    },

    /**
     * Download Windows Outlook .htm file
     */
    downloadOutlookHtm(htmlContent, filename = 'signature') {
      const content = this.generateOutlookHtm(htmlContent);
      downloadTextFile(content, `${filename}.htm`, 'text/html;charset=utf-8');
    },

    /**
     * Download Mozilla Thunderbird HTML snippet
     */
    downloadThunderbirdHtml(htmlContent, filename = 'thunderbird-signature') {
      downloadTextFile(htmlContent, `${filename}.html`, 'text/html;charset=utf-8');
    },

    /**
     * Generate Google Workspace Apps Script for domain-wide or individual deployment
     */
    generateGoogleAppsScript(htmlContent, userEmail = 'user@yourdomain.com') {
      const escapedHtml = JSON.stringify(htmlContent);
      return `/**
 * Google Workspace Domain Signature Deployer
 * Auto-generated by MailCraft Studio (https://mailcraft.dev)
 * 
 * Instructions:
 * 1. Open Google Apps Script (https://script.google.com)
 * 2. Paste this code into Code.gs
 * 3. In Services (+), add the "Gmail API" (v1) and "Admin Directory API" (v1)
 * 4. Run deployDomainSignatures() or deploySingleSignature()
 */

const SIGNATURE_HTML = ${escapedHtml};

/**
 * Deploy signature to a single user
 */
function deploySingleSignature(targetEmail) {
  const email = targetEmail || '${userEmail}';
  try {
    const sendAsResource = {
      signature: SIGNATURE_HTML
    };
    Gmail.Users.Settings.SendAs.patch(sendAsResource, 'me', email);
    Logger.log('Successfully applied signature to: ' + email);
  } catch (err) {
    Logger.log('Error deploying signature to ' + email + ': ' + err.message);
  }
}

/**
 * Batch deploy signature to all active users in domain (Admin Directory API required)
 */
function deployDomainSignatures() {
  try {
    let pageToken;
    let totalUpdated = 0;
    
    do {
      const response = AdminDirectory.Users.list({
        customer: 'my_customer',
        maxResults: 100,
        pageToken: pageToken,
        query: 'isSuspended=false'
      });

      const users = response.users || [];
      for (let i = 0; i < users.length; i++) {
        const u = users[i];
        try {
          Gmail.Users.Settings.SendAs.patch({ signature: SIGNATURE_HTML }, u.primaryEmail, u.primaryEmail);
          Logger.log('[' + (i + 1) + '] Signature applied to: ' + u.primaryEmail);
          totalUpdated++;
          Utilities.sleep(200); // Rate limit protection
        } catch (e) {
          Logger.log('Failed for ' + u.primaryEmail + ': ' + e.message);
        }
      }
      pageToken = response.nextPageToken;
    } while (pageToken);

    Logger.log('Finished domain deployment. Total users updated: ' + totalUpdated);
  } catch (err) {
    Logger.log('Domain deployment error: ' + err.message);
  }
}
`.trim();
    },

    /**
     * Download Google Apps Script file (.gs)
     */
    downloadGoogleAppsScript(htmlContent, userEmail) {
      const code = this.generateGoogleAppsScript(htmlContent, userEmail);
      downloadTextFile(code, 'MailCraft_Google_Workspace_Deployer.gs', 'text/javascript;charset=utf-8');
    },

    /**
     * Generate Microsoft 365 Exchange Online PowerShell deployment script
     */
    generateExchangePowerShell(htmlContent, userEmail = 'user@yourdomain.com') {
      const b64Html = (typeof btoa !== 'undefined') ? btoa(unescape(encodeURIComponent(htmlContent))) : Buffer.from(htmlContent).toString('base64');
      return `# =========================================================================
# Microsoft 365 / Exchange Online Signature Deployer
# Auto-generated by MailCraft Studio (https://mailcraft.dev)
# =========================================================================
# Requirements:
# 1. Open PowerShell 7+ or Windows PowerShell as Administrator
# 2. Run: Install-Module -Name ExchangeOnlineManagement -Scope CurrentUser
# 3. Run this script to connect and deploy signature
# =========================================================================

# Connect to Exchange Online
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -ShowBanner:$false

# Signature HTML payload (Base64 Encoded for safe transport)
$Base64Html = "${b64Html}"
$SignatureHtml = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Base64Html))

# Target user or set to $null for all mailbox users
$TargetUser = "${userEmail}"

if ($TargetUser -and $TargetUser -ne "user@yourdomain.com") {
    Write-Host "Deploying signature to: $TargetUser" -ForegroundColor Cyan
    Set-MailboxMessageConfiguration -Identity $TargetUser \`
        -AutoAddSignature $true \`
        -AutoAddSignatureOnReply $true \`
        -SignatureHtml $SignatureHtml
    Write-Host "Done! Signature successfully set for $TargetUser" -ForegroundColor Green
} else {
    Write-Host "Deploying signature to all active Exchange mailboxes..." -ForegroundColor Cyan
    $Mailboxes = Get-Mailbox -ResultSize Unlimited -RecipientTypeDetails UserMailbox
    $Count = 0
    foreach ($mb in $Mailboxes) {
        Write-Host "Applying to: $($mb.UserPrincipalName)..."
        Set-MailboxMessageConfiguration -Identity $mb.UserPrincipalName \`
            -AutoAddSignature $true \`
            -AutoAddSignatureOnReply $true \`
            -SignatureHtml $SignatureHtml
        $Count++
    }
    Write-Host "Finished! Updated $Count mailboxes." -ForegroundColor Green
}

Disconnect-ExchangeOnline -Confirm:$false
`.trim();
    },

    /**
     * Download Microsoft 365 PowerShell script (.ps1)
     */
    downloadExchangePowerShell(htmlContent, userEmail) {
      const code = this.generateExchangePowerShell(htmlContent, userEmail);
      downloadTextFile(code, 'Deploy_Microsoft365_Signature.ps1', 'text/plain;charset=utf-8');
    },

    /**
     * Bundle and download the complete Chrome Extension package as a ZIP
     */
    async downloadChromeExtensionZip(state = {}) {
      if (typeof ZipBuilder === 'undefined') {
        console.error('ZipBuilder not loaded');
        return;
      }

      // Try fetching local extension files if running on web server / localhost
      let defaultAvatarContent = '';
      let iconsContent = '';
      let presetsContent = '';
      let sigEngineContent = '';
      let popupHtmlContent = '';
      let popupCssContent = '';
      let popupJsContent = '';
      let contentJsContent = '';
      let manifestContent = '';
      let readmeContent = '';

      try {
        const [
          resAvatar, resIcons, resPresets, resEngine,
          resPopupHtml, resPopupCss, resPopupJs, resContentJs, resManifest, resReadme
        ] = await Promise.all([
          fetch('extension/default-avatar.js').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/icons.js').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/presets.js').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/signature-engine.js').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/popup.html').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/popup.css').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/popup.js').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/content.js').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/manifest.json').then(r => r.ok ? r.text() : '').catch(() => ''),
          fetch('extension/README.md').then(r => r.ok ? r.text() : '').catch(() => '')
        ]);

        defaultAvatarContent = resAvatar;
        iconsContent = resIcons;
        presetsContent = resPresets;
        sigEngineContent = resEngine;
        popupHtmlContent = resPopupHtml;
        popupCssContent = resPopupCss;
        popupJsContent = resPopupJs;
        contentJsContent = resContentJs;
        manifestContent = resManifest;
        readmeContent = resReadme;
      } catch (err) {
        console.warn('Could not fetch extension files via HTTP, using bundled memory fallbacks:', err);
      }

      // Fallbacks if not fetched via HTTP
      if (!manifestContent) {
        manifestContent = `{
  "manifest_version": 3,
  "name": "MailCraft Studio - Email Signature Switcher",
  "version": "2.0.0",
  "description": "1-Click inject and switch pixel-perfect, retina-ready email signatures in Gmail and Outlook Web.",
  "permissions": [
    "activeTab",
    "storage",
    "scripting"
  ],
  "host_permissions": [
    "https://mail.google.com/*",
    "https://outlook.live.com/*",
    "https://outlook.office.com/*",
    "https://outlook.office365.com/*"
  ],
  "action": {
    "default_popup": "popup.html",
    "default_title": "MailCraft Signature Switcher"
  },
  "content_scripts": [
    {
      "matches": [
        "https://mail.google.com/*",
        "https://outlook.live.com/*",
        "https://outlook.office.com/*",
        "https://outlook.office365.com/*"
      ],
      "js": ["content.js"],
      "run_at": "document_idle"
    }
  ]
}`;
      }

      if (!popupHtmlContent) {
        popupHtmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MailCraft Signature Switcher</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500;600;700;800&family=JetBrains+Mono:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,400&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="popup.css">
</head>
<body>
  <div class="popup-container">
    <header class="popup-header">
      <div class="header-brand">
        <span class="prompt-symbol">$</span>
        <span class="brand-title">MailCraft Studio</span>
      </div>
      <span class="version-tag">v2.0.0</span>
    </header>
    <div class="form-group">
      <label class="form-label" for="profileSelect">Active Signature Profile</label>
      <select id="profileSelect" class="form-select"></select>
    </div>
    <div class="preview-box">
      <div class="preview-header">
        <span class="preview-label">LIVE SIGNATURE PREVIEW</span>
        <span class="status-dot"></span>
      </div>
      <div class="preview-content" id="miniPreviewContainer"></div>
    </div>
    <div class="action-grid">
      <button class="btn-primary" id="injectSignatureBtn" title="Inject into active Gmail / Outlook compose box">
        <span>⚡</span> Insert into Compose Box
      </button>
      <button class="btn-secondary" id="copyRichSignatureBtn" title="Copy rich HTML signature for any email client">
        <span>📋</span> Copy Rich Text
      </button>
    </div>
    <div class="status-msg" id="statusMessage"></div>
    <footer class="popup-footer">
      <a href="https://mailcraftstudio.vercel.app/studio.html" target="_blank" class="footer-link">Open Full Studio ↗</a>
      <span class="privacy-note">100% Client-Side</span>
    </footer>
  </div>
  <script src="default-avatar.js"></script>
  <script src="icons.js"></script>
  <script src="presets.js"></script>
  <script src="signature-engine.js"></script>
  <script src="popup.js"></script>
</body>
</html>`;
      }

      if (!contentJsContent) {
        contentJsContent = `chrome.runtime.onMessage.addListener((req, sender, sendRes) => {
  if (req.action === 'INJECT_SIGNATURE') {
    const compose = document.querySelector('.Am.Al.editable, div[aria-label="Message Body"], div[role="textbox"]');
    if (compose) {
      const old = compose.querySelector('.mailcraft-injected-signature');
      if (old) old.remove();
      const wrap = document.createElement('div');
      wrap.className = 'mailcraft-injected-signature';
      wrap.style.marginTop = '16px';
      wrap.innerHTML = req.html;
      compose.appendChild(wrap);
      compose.dispatchEvent(new Event('input', { bubbles: true }));
      sendRes({ success: true });
    } else {
      sendRes({ success: false });
    }
  }
  return true;
});`;
      }

      if (!readmeContent) {
        readmeContent = `# MailCraft Chrome Extension (Manifest V3)
1. Open chrome://extensions
2. Turn on "Developer mode" in the top-right corner.
3. Click "Load unpacked" and select this folder.
4. Click the extension icon in your toolbar to switch signatures and 1-click inject into Gmail/Outlook!`;
      }

      const files = [
        { name: 'manifest.json', content: manifestContent },
        { name: 'popup.html', content: popupHtmlContent },
        { name: 'popup.css', content: popupCssContent },
        { name: 'popup.js', content: popupJsContent },
        { name: 'content.js', content: contentJsContent },
        { name: 'default-avatar.js', content: defaultAvatarContent },
        { name: 'icons.js', content: iconsContent },
        { name: 'presets.js', content: presetsContent },
        { name: 'signature-engine.js', content: sigEngineContent },
        { name: 'README.md', content: readmeContent }
      ];

      ZipBuilder.downloadZip(files, 'MailCraft_Studio_Chrome_Extension.zip');
    }
  };

  return AdminTools;
}));
