/**
 * MailCraft Studio - Enterprise Deployment & Desktop Signature File Exporter
 * Generates ready-to-run Google Apps Scripts, Microsoft 365 Exchange PowerShell,
 * macOS Apple Mail (.mailsignature), Outlook (.htm), and Thunderbird files.
 * 100% client-side compilation & zero data transmission.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], factory);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.AdminTools = factory();
  }
}(typeof self !== 'undefined' ? self : this, function() {
  'use strict';

  function generateUUID() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      const r = Math.random() * 16 | 0;
      const v = c === 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16).toUpperCase();
    });
  }

  function downloadTextFile(content, filename, mimeType = 'text/plain;charset=utf-8') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 200);
  }

  const AdminTools = {
    /**
     * Generate macOS Apple Mail .mailsignature content with RFC 822 / MIME header wrapper
     */
    generateAppleMailSignature(htmlContent) {
      const uuid = generateUUID();
      const headers = [
        'Content-Type: text/html; charset=utf-8',
        'Content-Transfer-Encoding: 7bit',
        `Message-Id: <${uuid}@mailcraft.local>`,
        'Mime-Version: 1.0 (Apple Message signature)',
        '',
        htmlContent
      ];
      return headers.join('\r\n');
    },

    /**
     * Download Apple Mail .mailsignature file
     */
    downloadAppleMailSignature(htmlContent, filename = 'signature') {
      const content = this.generateAppleMailSignature(htmlContent);
      const uuid = generateUUID();
      downloadTextFile(content, `${uuid}.mailsignature`, 'application/octet-stream');
    },

    /**
     * Generate Windows Outlook .htm signature file
     */
    generateOutlookHtm(htmlContent) {
      return `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">\r\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8"></HEAD><BODY>\r\n${htmlContent}\r\n</BODY></HTML>`;
    },

    /**
     * Download Windows Outlook .htm file
     */
    downloadOutlookHtm(htmlContent, filename = 'signature') {
      const content = this.generateOutlookHtm(htmlContent);
      downloadTextFile(content, `${filename}.htm`, 'text/html;charset=utf-8');
    },

    /**
     * Download Mozilla Thunderbird HTML snippet
     */
    downloadThunderbirdHtml(htmlContent, filename = 'thunderbird-signature') {
      downloadTextFile(htmlContent, `${filename}.html`, 'text/html;charset=utf-8');
    },

    /**
     * Generate Google Workspace Apps Script for domain-wide or individual deployment
     */
    generateGoogleAppsScript(htmlContent, userEmail = 'user@yourdomain.com') {
      const escapedHtml = JSON.stringify(htmlContent);
      return `/**
 * Google Workspace Domain Signature Deployer
 * Auto-generated by MailCraft Studio (https://mailcraft.dev)
 * 
 * Instructions:
 * 1. Open Google Apps Script (https://script.google.com)
 * 2. Paste this code into Code.gs
 * 3. In Services (+), add the "Gmail API" (v1) and "Admin Directory API" (v1)
 * 4. Run deployDomainSignatures() or deploySingleSignature()
 */

const SIGNATURE_HTML = ${escapedHtml};

/**
 * Deploy signature to a single user
 */
function deploySingleSignature(targetEmail) {
  const email = targetEmail || '${userEmail}';
  try {
    const sendAsResource = {
      signature: SIGNATURE_HTML
    };
    Gmail.Users.Settings.SendAs.patch(sendAsResource, 'me', email);
    Logger.log('Successfully applied signature to: ' + email);
  } catch (err) {
    Logger.log('Error deploying signature to ' + email + ': ' + err.message);
  }
}

/**
 * Batch deploy signature to all active users in domain (Admin Directory API required)
 */
function deployDomainSignatures() {
  try {
    let pageToken;
    let totalUpdated = 0;
    
    do {
      const response = AdminDirectory.Users.list({
        customer: 'my_customer',
        maxResults: 100,
        pageToken: pageToken,
        query: 'isSuspended=false'
      });

      const users = response.users || [];
      for (let i = 0; i < users.length; i++) {
        const u = users[i];
        try {
          Gmail.Users.Settings.SendAs.patch({ signature: SIGNATURE_HTML }, u.primaryEmail, u.primaryEmail);
          Logger.log('[' + (i + 1) + '] Signature applied to: ' + u.primaryEmail);
          totalUpdated++;
          Utilities.sleep(200); // Rate limit protection
        } catch (e) {
          Logger.log('Failed for ' + u.primaryEmail + ': ' + e.message);
        }
      }
      pageToken = response.nextPageToken;
    } while (pageToken);

    Logger.log('Finished domain deployment. Total users updated: ' + totalUpdated);
  } catch (err) {
    Logger.log('Domain deployment error: ' + err.message);
  }
}
`.trim();
    },

    /**
     * Download Google Apps Script file (.gs)
     */
    downloadGoogleAppsScript(htmlContent, userEmail) {
      const code = this.generateGoogleAppsScript(htmlContent, userEmail);
      downloadTextFile(code, 'MailCraft_Google_Workspace_Deployer.gs', 'text/javascript;charset=utf-8');
    },

    /**
     * Generate Microsoft 365 Exchange Online PowerShell deployment script
     */
    generateExchangePowerShell(htmlContent, userEmail = 'user@yourdomain.com') {
      const b64Html = (typeof btoa !== 'undefined') ? btoa(unescape(encodeURIComponent(htmlContent))) : Buffer.from(htmlContent).toString('base64');
      return `# =========================================================================
# Microsoft 365 / Exchange Online Signature Deployer
# Auto-generated by MailCraft Studio (https://mailcraft.dev)
# =========================================================================
# Requirements:
# 1. Open PowerShell 7+ or Windows PowerShell as Administrator
# 2. Run: Install-Module -Name ExchangeOnlineManagement -Scope CurrentUser
# 3. Run this script to connect and deploy signature
# =========================================================================

# Connect to Exchange Online
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -ShowBanner:$false

# Signature HTML payload (Base64 Encoded for safe transport)
$Base64Html = "${b64Html}"
$SignatureHtml = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Base64Html))

# Target user or set to $null for all mailbox users
$TargetUser = "${userEmail}"

if ($TargetUser -and $TargetUser -ne "user@yourdomain.com") {
    Write-Host "Deploying signature to: $TargetUser" -ForegroundColor Cyan
    Set-MailboxMessageConfiguration -Identity $TargetUser \`
        -AutoAddSignature $true \`
        -AutoAddSignatureOnReply $true \`
        -SignatureHtml $SignatureHtml
    Write-Host "Done! Signature successfully set for $TargetUser" -ForegroundColor Green
} else {
    Write-Host "Deploying signature to all active Exchange mailboxes..." -ForegroundColor Cyan
    $Mailboxes = Get-Mailbox -ResultSize Unlimited -RecipientTypeDetails UserMailbox
    $Count = 0
    foreach ($mb in $Mailboxes) {
        Write-Host "Applying to: $($mb.UserPrincipalName)..."
        Set-MailboxMessageConfiguration -Identity $mb.UserPrincipalName \`
            -AutoAddSignature $true \`
            -AutoAddSignatureOnReply $true \`
            -SignatureHtml $SignatureHtml
        $Count++
    }
    Write-Host "Finished! Updated $Count mailboxes." -ForegroundColor Green
}

Disconnect-ExchangeOnline -Confirm:$false
`.trim();
    },

    /**
     * Download Microsoft 365 PowerShell script (.ps1)
     */
    downloadExchangePowerShell(htmlContent, userEmail) {
      const code = this.generateExchangePowerShell(htmlContent, userEmail);
      downloadTextFile(code, 'Deploy_Microsoft365_Signature.ps1', 'text/plain;charset=utf-8');
    }
  };

  return AdminTools;
}));
